/**
 * MedicalDisclaimer — Required legal disclaimer on all AI outputs and reports.
 * Must be visible on: every screening module, AI analysis panel, doctor inbox,
 * parent reports, 4D reports, and any page showing clinical findings.
 */

import { AlertTriangle, Shield } from 'lucide-react'

type DisclaimerVariant = 'inline' | 'banner' | 'compact' | 'report'

interface MedicalDisclaimerProps {
  variant?: DisclaimerVariant
  className?: string
}

const SCREENING_DISCLAIMER =
  'AI-assisted findings are for screening purposes only and do not constitute a medical diagnosis. All findings must be confirmed by a qualified medical professional.'

const REPORT_DISCLAIMER =
  'This report is generated by an AI-assisted screening tool and is intended for preliminary screening only. It does not replace professional medical evaluation. Consult a qualified healthcare provider for diagnosis and treatment decisions.'

const NURSE_DISCLAIMER =
  'AI suggestions are aids only. Use your clinical judgment for all observations.'

export function MedicalDisclaimer({ variant = 'inline', className = '' }: MedicalDisclaimerProps) {
  if (variant === 'compact') {
    return (
      <p className={`flex items-center gap-1 text-[9px] text-amber-600 ${className}`}>
        <AlertTriangle className="h-3 w-3 flex-shrink-0" />
        {NURSE_DISCLAIMER}
      </p>
    )
  }

  if (variant === 'banner') {
    return (
      <div className={`rounded-lg border border-amber-200 bg-amber-50 px-4 py-2.5 ${className}`}>
        <div className="flex items-start gap-2">
          <Shield className="mt-0.5 h-4 w-4 flex-shrink-0 text-amber-600" />
          <div>
            <p className="text-xs font-semibold text-amber-800">Medical Disclaimer</p>
            <p className="mt-0.5 text-[11px] leading-relaxed text-amber-700">
              {SCREENING_DISCLAIMER}
            </p>
          </div>
        </div>
      </div>
    )
  }

  if (variant === 'report') {
    return (
      <div className={`rounded-lg border-2 border-amber-300 bg-amber-50 px-5 py-3 ${className}`}>
        <div className="flex items-start gap-3">
          <Shield className="mt-0.5 h-5 w-5 flex-shrink-0 text-amber-600" />
          <div>
            <p className="text-sm font-bold text-amber-900">Important Medical Notice</p>
            <p className="mt-1 text-xs leading-relaxed text-amber-800">
              {REPORT_DISCLAIMER}
            </p>
            <p className="mt-2 text-[10px] text-amber-600">
              SKIDS Screen V3 | AI-Assisted Pediatric Health Screening | Not a Diagnostic Tool
            </p>
          </div>
        </div>
      </div>
    )
  }

  // Default: inline
  return (
    <div className={`flex items-center gap-1.5 rounded-md bg-amber-50 px-3 py-1.5 ${className}`}>
      <AlertTriangle className="h-3.5 w-3.5 flex-shrink-0 text-amber-500" />
      <p className="text-[10px] text-amber-700">
        {SCREENING_DISCLAIMER}
      </p>
    </div>
  )
}
