export { extractFaceSignal, computeHeartRateCHROM } from './rppg'
export { analyzeRedReflex } from './vision'
export type { RedReflexResult } from './vision'
export { extractAudioFeatures, classifyCough } from './audio'
export type { AudioFeatures, CoughClassification } from './audio'
export { segmentWound } from './skin'
export type { WoundSegmentationResult } from './skin'
export { analyzeMotorPerformance } from './motor'
export type { MotorAnalysisResult } from './motor'
export { analyzeEarImage } from './ear'
export type { EarAnalysisResult } from './ear'
export { extractFacePosition, analyzeGazeStability, computeNeuroResults } from './neurodevelopment'
export type { EngagementMetrics, NeuroScreeningResult } from './neurodevelopment'

// New AI modules
export { analyzeClinicalColors, mapSuggestionsToChipIds } from './clinical-color'
export { heightForAge, weightForAge, bmiForAge, classifySpO2, classifyAnemia } from './anthropometry'
export { extractKeyFrames } from './video-frames'
export { playTone, calculatePTA, generateAudiometryResult, classifyHearingLoss, getHearingColor, suggestHearingChips, TEST_FREQUENCIES } from './audiometry'
export type { AudiometryThreshold, AudiometryResult } from './audiometry'
