#!/usr/bin/env python3
"""Split the publishable DuckDB SQL into a per-statement bash runner.

Called from .github/workflows/analytics-publishable.yml. The input is the
fully-substituted DuckDB script (preamble + a series of COPY statements).
The output is a bash script that:

  - runs the preamble + one COPY at a time in separate `duckdb :memory:`
    invocations, so a single failing table (e.g. empty source) does not
    abort the entire run;
  - counts successes + failures;
  - exits 0 when at least one statement succeeded, exits 1 only if all of
    them failed.

Lives outside the YAML because GitHub Actions scans the entire `run:`
body for `${{ ... }}` expression syntax — embedding a multi-line Python
heredoc that contains bash `${var:-default}` parameter expansion trips
the parser.
"""

from __future__ import annotations
import json
import re
import sys


def main() -> int:
    if len(sys.argv) != 3:
        print("usage: split-publishable-sql.py <input.sql> <output.sh>", file=sys.stderr)
        return 2

    in_path, out_path = sys.argv[1], sys.argv[2]
    with open(in_path, "r", encoding="utf-8") as f:
        sql = f.read()

    idx = sql.find("COPY ")
    if idx < 0:
        print("no COPY statements in publishable SQL", file=sys.stderr)
        return 1

    preamble = sql[:idx].strip()
    rest = sql[idx:]
    # Split at `;` followed by any mix of whitespace and `--` comment
    # lines and a following `COPY `. The worker prefixes each COPY with
    # a `-- N) ...` comment for readability.
    chunks = re.split(r";[ \t]*\n(?:[ \t]*(?:--[^\n]*)?\n)*(?=COPY )", rest)
    chunks = [c.rstrip().rstrip(";").strip() for c in chunks if c.strip()]

    lines: list[str] = [
        "#!/usr/bin/env bash",
        "# Generated by scripts/split-publishable-sql.py — do not edit.",
        "set +e",
        "failed=0",
        "succeeded=0",
    ]

    for i, chunk in enumerate(chunks):
        match = re.search(r"TO\s+'([^']+)'", chunk)
        label = match.group(1) if match else f"statement-{i}"
        lines.append(f'echo "::group::COPY {label}"')
        # Unquoted heredoc so DuckDB sees real multi-line SQL. The
        # preamble and chunk are inlined with actual newlines (no JSON
        # string escape). We use a unique terminator per statement in
        # case a chunk ever contains the default "SQL" marker.
        heredoc = f"SQL_{i}"
        lines.append(f"duckdb :memory: <<'{heredoc}'")
        lines.append(preamble)
        lines.append(chunk + ";")
        lines.append(heredoc)
        lines.append("rc=$?")
        lines.append('echo "exit code: $rc"')
        lines.append("if [[ $rc -ne 0 ]]; then failed=$((failed + 1)); else succeeded=$((succeeded + 1)); fi")
        lines.append('echo "::endgroup::"')

    lines += [
        'echo "---"',
        'echo "succeeded: $succeeded, failed: $failed, total: ' + str(len(chunks)) + '"',
        "if [[ $failed -gt 0 ]]; then",
        '  echo "::warning::$failed of ' + str(len(chunks)) + " publishable COPY statements failed "
        '(likely empty source tables or schema drift)."',
        "fi",
        "# Only fail the job if ZERO statements succeeded.",
        "if [[ $succeeded -eq 0 ]]; then",
        '  echo "::error::All publishable COPY statements failed."',
        "  exit 1",
        "fi",
    ]

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    print(f"wrote {out_path} with {len(chunks)} COPY statements")
    return 0


if __name__ == "__main__":
    sys.exit(main())
